//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV
{
   public static partial class CvInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern int cveLineIteratorGetCount(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveLineIteratorSetCount(
        IntPtr obj,  
        int val);
     
   }

   public partial class LineIterator
   {

     /// <summary>
     /// The total number of pixels in the line
     /// </summary>
     public int Count
     {
        get { return CvInvoke.cveLineIteratorGetCount(_ptr); } 
        set { CvInvoke.cveLineIteratorSetCount(_ptr, value); }
     }
     
   }
}
