//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV
{
   public static partial class CvInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern float cveTonemapGetGamma(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveTonemapSetGamma(
        IntPtr obj,  
        float val);
     
   }

   public partial class Tonemap
   {

     /// <summary>
     /// Positive value for gamma correction. Gamma value of 1.0 implies no correction, gamma equal to 2.2f is suitable for most displays.
     /// </summary>
     public float Gamma
     {
        get { return CvInvoke.cveTonemapGetGamma(_ptr); } 
        set { CvInvoke.cveTonemapSetGamma(_ptr, value); }
     }
     
   }
}
