//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV
{
   public static partial class CvInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern float cveTrackerDaSiamRPNGetTrackingScore(IntPtr obj);
     
   }

   public partial class TrackerDaSiamRPN
   {

     /// <summary>
    /// Tracking score
     /// </summary>
     public float TrackingScore
     {
        get { return CvInvoke.cveTrackerDaSiamRPNGetTrackingScore(_ptr); } 
     }
     
   }
}
