//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.XPhoto
{
   public static partial class XPhotoInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern float cveGrayworldWBGetSaturationThreshold(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveGrayworldWBSetSaturationThreshold(
        IntPtr obj,  
        float val);
     
   }

   public partial class GrayworldWB
   {

     /// <summary>
     /// Maximum saturation for a pixel to be included in the gray-world assumption
     /// </summary>
     public float SaturationThreshold
     {
        get { return XPhotoInvoke.cveGrayworldWBGetSaturationThreshold(_ptr); } 
        set { XPhotoInvoke.cveGrayworldWBSetSaturationThreshold(_ptr, value); }
     }
     
   }
}
