//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.Linemod
{
   public static partial class LinemodInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern int cveDetectorPyramidLevels(IntPtr obj);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern int cveDetectorNumTemplates(IntPtr obj);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern int cveDetectorNumClasses(IntPtr obj);
     
   }

   public partial class Detector
   {

     /// <summary>
     /// Get number of pyramid levels used by this detector.
     /// </summary>
     public int PyramidLevels
     {
        get { return LinemodInvoke.cveDetectorPyramidLevels(_ptr); } 
     }
     
     /// <summary>
     /// Get number of templates.
     /// </summary>
     public int NumTemplates
     {
        get { return LinemodInvoke.cveDetectorNumTemplates(_ptr); } 
     }
     
     /// <summary>
     /// Get number of classes.
     /// </summary>
     public int NumClasses
     {
        get { return LinemodInvoke.cveDetectorNumClasses(_ptr); } 
     }
     
   }
}
