//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.Dnn
{
   public static partial class DnnInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern void cveTextRecognitionModelGetDecodeType(IntPtr obj, IntPtr str);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern void cveTextRecognitionModelSetDecodeType(IntPtr obj, IntPtr str);
     
   }

   public partial class TextRecognitionModel
   {

     /// <summary>
     /// Decode type
     /// </summary>
     public String DecodeType
     {
        get 
        { 
           using (CvString s = new CvString())
           {  
              DnnInvoke.cveTextRecognitionModelGetDecodeType(_ptr, s); 
              return s.ToString();
           }
        } 
        set
        {
           using (CvString s = new CvString(value))
           {  
              DnnInvoke.cveTextRecognitionModelSetDecodeType(_ptr, s); 
           }
        }
     }
     
   }
}
