//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.Dnn
{
   public static partial class DnnInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     [return: MarshalAs(CvInvoke.BoolMarshalType)]
     internal static extern bool cveDetectionModelGetNmsAcrossClasses(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveDetectionModelSetNmsAcrossClasses(
        IntPtr obj, 
        [MarshalAs(CvInvoke.BoolMarshalType)] 
        bool val);
     
   }

   public partial class DetectionModel
   {

     /// <summary>
     /// It true, will perform non-maximum suppression across classes
     /// </summary>
     public bool NmsAcrossClasses
     {
        get { return DnnInvoke.cveDetectionModelGetNmsAcrossClasses(_ptr); } 
        set { DnnInvoke.cveDetectionModelSetNmsAcrossClasses(_ptr, value); }
     }
     
   }
}
