//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV
{
   public static partial class CvInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetM00(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetM00(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetM10(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetM10(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetM01(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetM01(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetM20(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetM20(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetM11(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetM11(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetM02(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetM02(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetM30(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetM30(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetM21(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetM21(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetM12(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetM12(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetM03(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetM03(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetMu20(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetMu20(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetMu11(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetMu11(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetMu02(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetMu02(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetMu30(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetMu30(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetMu21(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetMu21(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetMu12(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetMu12(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetMu03(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetMu03(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetNu20(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetNu20(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetNu11(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetNu11(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetNu02(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetNu02(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetNu30(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetNu30(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetNu21(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetNu21(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetNu12(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetNu12(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveMomentsGetNu03(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMomentsSetNu03(
        IntPtr obj,  
        double val);
     
   }

   public partial class Moments
   {

     /// <summary>
     /// Spatial Moment M00
     /// </summary>
     public double M00
     {
        get { return CvInvoke.cveMomentsGetM00(_ptr); } 
        set { CvInvoke.cveMomentsSetM00(_ptr, value); }
     }
     
     /// <summary>
     /// Spatial Moment M10
     /// </summary>
     public double M10
     {
        get { return CvInvoke.cveMomentsGetM10(_ptr); } 
        set { CvInvoke.cveMomentsSetM10(_ptr, value); }
     }
     
     /// <summary>
     /// Spatial Moment M01
     /// </summary>
     public double M01
     {
        get { return CvInvoke.cveMomentsGetM01(_ptr); } 
        set { CvInvoke.cveMomentsSetM01(_ptr, value); }
     }
     
     /// <summary>
     /// Spatial Moment M20
     /// </summary>
     public double M20
     {
        get { return CvInvoke.cveMomentsGetM20(_ptr); } 
        set { CvInvoke.cveMomentsSetM20(_ptr, value); }
     }
     
     /// <summary>
     /// Spatial Moment M11
     /// </summary>
     public double M11
     {
        get { return CvInvoke.cveMomentsGetM11(_ptr); } 
        set { CvInvoke.cveMomentsSetM11(_ptr, value); }
     }
     
     /// <summary>
     /// Spatial Moment M02
     /// </summary>
     public double M02
     {
        get { return CvInvoke.cveMomentsGetM02(_ptr); } 
        set { CvInvoke.cveMomentsSetM02(_ptr, value); }
     }
     
     /// <summary>
     /// Spatial Moment M30
     /// </summary>
     public double M30
     {
        get { return CvInvoke.cveMomentsGetM30(_ptr); } 
        set { CvInvoke.cveMomentsSetM30(_ptr, value); }
     }
     
     /// <summary>
     /// Spatial Moment M21
     /// </summary>
     public double M21
     {
        get { return CvInvoke.cveMomentsGetM21(_ptr); } 
        set { CvInvoke.cveMomentsSetM21(_ptr, value); }
     }
     
     /// <summary>
     /// Spatial Moment M12
     /// </summary>
     public double M12
     {
        get { return CvInvoke.cveMomentsGetM12(_ptr); } 
        set { CvInvoke.cveMomentsSetM12(_ptr, value); }
     }
     
     /// <summary>
     /// Spatial Moment M03
     /// </summary>
     public double M03
     {
        get { return CvInvoke.cveMomentsGetM03(_ptr); } 
        set { CvInvoke.cveMomentsSetM03(_ptr, value); }
     }
     
     /// <summary>
     /// Central Moment Mu20
     /// </summary>
     public double Mu20
     {
        get { return CvInvoke.cveMomentsGetMu20(_ptr); } 
        set { CvInvoke.cveMomentsSetMu20(_ptr, value); }
     }
     
     /// <summary>
     /// Central Moment Mu11
     /// </summary>
     public double Mu11
     {
        get { return CvInvoke.cveMomentsGetMu11(_ptr); } 
        set { CvInvoke.cveMomentsSetMu11(_ptr, value); }
     }
     
     /// <summary>
     /// Central Moment Mu02
     /// </summary>
     public double Mu02
     {
        get { return CvInvoke.cveMomentsGetMu02(_ptr); } 
        set { CvInvoke.cveMomentsSetMu02(_ptr, value); }
     }
     
     /// <summary>
     /// Central Moment Mu30
     /// </summary>
     public double Mu30
     {
        get { return CvInvoke.cveMomentsGetMu30(_ptr); } 
        set { CvInvoke.cveMomentsSetMu30(_ptr, value); }
     }
     
     /// <summary>
     /// Central Moment Mu21
     /// </summary>
     public double Mu21
     {
        get { return CvInvoke.cveMomentsGetMu21(_ptr); } 
        set { CvInvoke.cveMomentsSetMu21(_ptr, value); }
     }
     
     /// <summary>
     /// Central Moment Mu12
     /// </summary>
     public double Mu12
     {
        get { return CvInvoke.cveMomentsGetMu12(_ptr); } 
        set { CvInvoke.cveMomentsSetMu12(_ptr, value); }
     }
     
     /// <summary>
     /// Central Moment Mu03
     /// </summary>
     public double Mu03
     {
        get { return CvInvoke.cveMomentsGetMu03(_ptr); } 
        set { CvInvoke.cveMomentsSetMu03(_ptr, value); }
     }
     
     /// <summary>
     /// Central Normalized Moment Nu20
     /// </summary>
     public double Nu20
     {
        get { return CvInvoke.cveMomentsGetNu20(_ptr); } 
        set { CvInvoke.cveMomentsSetNu20(_ptr, value); }
     }
     
     /// <summary>
     /// Central Normalized Moment Nu11
     /// </summary>
     public double Nu11
     {
        get { return CvInvoke.cveMomentsGetNu11(_ptr); } 
        set { CvInvoke.cveMomentsSetNu11(_ptr, value); }
     }
     
     /// <summary>
     /// Central Normalized Moment Nu02
     /// </summary>
     public double Nu02
     {
        get { return CvInvoke.cveMomentsGetNu02(_ptr); } 
        set { CvInvoke.cveMomentsSetNu02(_ptr, value); }
     }
     
     /// <summary>
     /// Central Normalized Moment Nu30
     /// </summary>
     public double Nu30
     {
        get { return CvInvoke.cveMomentsGetNu30(_ptr); } 
        set { CvInvoke.cveMomentsSetNu30(_ptr, value); }
     }
     
     /// <summary>
     /// Central Normalized Moment Nu21
     /// </summary>
     public double Nu21
     {
        get { return CvInvoke.cveMomentsGetNu21(_ptr); } 
        set { CvInvoke.cveMomentsSetNu21(_ptr, value); }
     }
     
     /// <summary>
     /// Central Normalized Moment Nu12
     /// </summary>
     public double Nu12
     {
        get { return CvInvoke.cveMomentsGetNu12(_ptr); } 
        set { CvInvoke.cveMomentsSetNu12(_ptr, value); }
     }
     
     /// <summary>
     /// Central Normalized Moment Nu03
     /// </summary>
     public double Nu03
     {
        get { return CvInvoke.cveMomentsGetNu03(_ptr); } 
        set { CvInvoke.cveMomentsSetNu03(_ptr, value); }
     }
     
   }
}
