//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.Dai
{
   public static partial class DaiInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     [return: MarshalAs(CvInvoke.BoolMarshalType)]
     internal static extern bool cveColorCameraGetInterleaved(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveColorCameraSetInterleaved(
        IntPtr obj, 
        [MarshalAs(CvInvoke.BoolMarshalType)] 
        bool val);
     
   }

   public partial class ColorCamera
   {

     /// <summary>
     /// True if the image pixels are interleaved
     /// </summary>
     public bool Interleaved
     {
        get { return DaiInvoke.cveColorCameraGetInterleaved(_ptr); } 
        set { DaiInvoke.cveColorCameraSetInterleaved(_ptr, value); }
     }
     
   }
}
