//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.Dai
{
   public static partial class DaiInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern UInt32 cveImgFrameGetWidth(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveImgFrameSetWidth(
        IntPtr obj,  
        UInt32 val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern UInt32 cveImgFrameGetHeight(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveImgFrameSetHeight(
        IntPtr obj,  
        UInt32 val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern UInt32 cveImgFrameGetInstanceNum(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveImgFrameSetInstanceNum(
        IntPtr obj,  
        UInt32 val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern UInt32 cveImgFrameGetCategory(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveImgFrameSetCategory(
        IntPtr obj,  
        UInt32 val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern Int64 cveImgFrameGetSequenceNum(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveImgFrameSetSequenceNum(
        IntPtr obj,  
        Int64 val);
     
   }

   public partial class ImgFrame
   {

     /// <summary>
     /// Image width
     /// </summary>
     public UInt32 Width
     {
        get { return DaiInvoke.cveImgFrameGetWidth(_ptr); } 
        set { DaiInvoke.cveImgFrameSetWidth(_ptr, value); }
     }
     
     /// <summary>
     /// Image height
     /// </summary>
     public UInt32 Height
     {
        get { return DaiInvoke.cveImgFrameGetHeight(_ptr); } 
        set { DaiInvoke.cveImgFrameSetHeight(_ptr, value); }
     }
     
     /// <summary>
     /// Instance number
     /// </summary>
     public UInt32 InstanceNum
     {
        get { return DaiInvoke.cveImgFrameGetInstanceNum(_ptr); } 
        set { DaiInvoke.cveImgFrameSetInstanceNum(_ptr, value); }
     }
     
     /// <summary>
     /// Image category
     /// </summary>
     public UInt32 Category
     {
        get { return DaiInvoke.cveImgFrameGetCategory(_ptr); } 
        set { DaiInvoke.cveImgFrameSetCategory(_ptr, value); }
     }
     
     /// <summary>
     /// Image sequence number
     /// </summary>
     public Int64 SequenceNum
     {
        get { return DaiInvoke.cveImgFrameGetSequenceNum(_ptr); } 
        set { DaiInvoke.cveImgFrameSetSequenceNum(_ptr, value); }
     }
     
   }
}
