//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.Dai
{
   public static partial class DaiInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern float cveMonoCameraGetFps(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveMonoCameraSetFps(
        IntPtr obj,  
        float val);
     
   }

   public partial class MonoCamera
   {

     /// <summary>
     /// The rate at which camera should produce frames
     /// </summary>
     public float Fps
     {
        get { return DaiInvoke.cveMonoCameraGetFps(_ptr); } 
        set { DaiInvoke.cveMonoCameraSetFps(_ptr, value); }
     }
     
   }
}
