//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.Stereo
{
   public static partial class StereoInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern QuasiDenseStereo.PropagationParameters cveQuasiDenseStereoGetParam(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveQuasiDenseStereoSetParam(
        IntPtr obj,  
        QuasiDenseStereo.PropagationParameters val);
     
   }

   public partial class QuasiDenseStereo
   {

     /// <summary>
     /// Parameters for the QuasiDenseStereo class
     /// </summary>
     public QuasiDenseStereo.PropagationParameters Param
     {
        get { return StereoInvoke.cveQuasiDenseStereoGetParam(_ptr); } 
        set { StereoInvoke.cveQuasiDenseStereoSetParam(_ptr, value); }
     }
     
   }
}
