//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.Dai
{
   public static partial class DaiInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern int cveNeuralNetworkGetNumInferenceThreads(IntPtr obj);
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveNeuralNetworkSetNumInferenceThreads(
        IntPtr obj,  
        int val);
     
   }

   public partial class NeuralNetwork
   {

     /// <summary>
     /// How many inference threads will be used to run the network, Zero means AUTO
     /// </summary>
     public int NumInferenceThreads
     {
        get { return DaiInvoke.cveNeuralNetworkGetNumInferenceThreads(_ptr); } 
        set { DaiInvoke.cveNeuralNetworkSetNumInferenceThreads(_ptr, value); }
     }
     
   }
}
