//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV
{
   public static partial class CvInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveQRCodeDetectorSetEpsX(
        IntPtr obj,  
        double val);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)]
     internal static extern void cveQRCodeDetectorSetEpsY(
        IntPtr obj,  
        double val);
     
   }

   public partial class QRCodeDetector
   {

     /// <summary>
     /// EpsX
     /// </summary>
	 /// <param name="value">The value</param>
     public void SetEpsX(double value)
     {
        CvInvoke.cveQRCodeDetectorSetEpsX(_ptr, value); 
     }
     
     /// <summary>
     /// EpsY
     /// </summary>
	 /// <param name="value">The value</param>
     public void SetEpsY(double value)
     {
        CvInvoke.cveQRCodeDetectorSetEpsY(_ptr, value); 
     }
     
   }
}
